export const GETSELLER = 'getSeller'
export const GETGOODS = 'getGoods'
export const GETRATINGS = 'getRatings'
export const GETADDRESS = 'getAddress'
export const GETCATEGORY = 'getCategory'
export const GETSHOPS = 'getShops'